### ISSUE TITLE
Sir kindly tell the reference paper for the same

### ISSUE THREAD

**Issue by rajnigupta-555** [KeivanKaboutari/AI-Beamforming#1]
Thank you for the code, pls tell us about the reference paper

**Comment by KeivanKaboutari** [comment]
Hi,

 

                The full version of the article has not been published yet. However, you can look at these proceeding papers:

 <https://scholar.google.com/citations?view_op=view_citation&hl=en&user=2DBDkJoAAAAJ&sortby=pubdate&citation_for_view=2DBDkJoAAAAJ:UeHWp8X0CEIC> Beamforming with Intelligent Metasurfaces: Operating Principles and Possible Implementations

K Kaboutari, A Abraray, S Maslovski

 <https://scholar.google.com/citations?view_op=view_citation&hl=en&user=2DBDkJoAAAAJ&sortby=pubdate&citation_for_view=2DBDkJoAAAAJ:YsMSGLbcyi4C> Chessboard Mushroom-Type Metasurface for Beamforming Applications

A Abraray, R Pereira, K Kaboutari, S Maslovski

 <https://scholar.google.com/citations?view_op=view_citation&hl=en&user=2DBDkJoAAAAJ&sortby=pubdate&citation_for_view=2DBDkJoAAAAJ:zYLM7Y9cAGgC> Analytical and numerical modeling of reconfigurable beamforming metasurfaces

M Maslovski, A Abraray, K Kaboutari, D Nunes, A Navarro

 <https://scholar.google.com/citations?view_op=view_citation&hl=en&user=2DBDkJoAAAAJ&sortby=pubdate&citation_for_view=2DBDkJoAAAAJ:5nxA0vEk-isC> Realization of Programmable Chessboard Mushroom-type Metasurface for Beamforming Applications

A Abraray, RAM Pereira, K Kaboutari, S Maslovski

 

 

Yours Sincerely

 

From: rajnigupta-555 ***@***.***> 
Sent: Saturday, August 26, 2023 6:15 AM
To: KeivanKaboutari/AI-Beamforming ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [KeivanKaboutari/AI-Beamforming] Sir kindly tell the reference paper for the same (Issue #1)

 

Thank you for the code, pls tell us about the reference paper

**Comment by KeivanKaboutari** [comment]
The reference paper has been published.
Kaboutari, K.; Abraray, A.; Maslovski, S. Numerically Optimized Fourier Transform-Based Beamforming Accelerated by Neural Networks. Appl. Sci. 2024, 14(7), 2866; https://doi.org/10.3390/app14072866.
